/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacesGUI;

import javax.swing.JOptionPane;
import usoBD.CRUD;
import usoBD.logginU;
import usoBD.sql;

/**
 *
 * @author fanma
 */
public class logginUsuarios extends javax.swing.JFrame {
    logginU Loggin;
    CRUD crud;
    /**
     * Creates new form usojLabel
     */
    public logginUsuarios() {
        initComponents();
        etiquetaEstado.setVisible(false);
        this.crud = new CRUD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        insertImagen3 = new practicas.tema2.insertImagen();
        etiquetaTitulo = new javax.swing.JLabel();
        etiquetaNombre1 = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        etiquetaCorreo = new javax.swing.JLabel();
        cajaCorreo = new javax.swing.JTextField();
        etiquetaContraseña = new javax.swing.JLabel();
        cajaContraseña = new javax.swing.JTextField();
        etiquetaEstado = new javax.swing.JLabel();
        Iniciar = new javax.swing.JButton();
        iconoTeacher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(350, 100));
        setResizable(false);
        setSize(new java.awt.Dimension(350, 100));

        insertImagen3.setPreferredSize(new java.awt.Dimension(750, 620));
        insertImagen3.setRutaImagen(new java.io.File("C:\\Users\\fanma\\OneDrive\\Documentos\\NetBeansProjects\\ImagenProyectoTopicos\\paulo-lopes-wpa-hallway-pixel-art (1).jpg"));

        etiquetaTitulo.setBackground(new java.awt.Color(255, 0, 255));
        etiquetaTitulo.setFont(new java.awt.Font("Unispace", 0, 36)); // NOI18N
        etiquetaTitulo.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTitulo.setText("BIENVENIDO");
        etiquetaTitulo.setOpaque(true);

        etiquetaNombre1.setBackground(new java.awt.Color(255, 51, 51));
        etiquetaNombre1.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        etiquetaNombre1.setForeground(new java.awt.Color(255, 255, 0));
        etiquetaNombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNombre1.setText("Nickname");
        etiquetaNombre1.setToolTipText("");
        etiquetaNombre1.setOpaque(true);

        cajaNombre.setBackground(new java.awt.Color(204, 204, 204));
        cajaNombre.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        cajaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNombreActionPerformed(evt);
            }
        });

        etiquetaCorreo.setBackground(new java.awt.Color(255, 51, 51));
        etiquetaCorreo.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        etiquetaCorreo.setForeground(new java.awt.Color(255, 255, 0));
        etiquetaCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaCorreo.setText("Correo");
        etiquetaCorreo.setToolTipText("");
        etiquetaCorreo.setOpaque(true);

        cajaCorreo.setBackground(new java.awt.Color(204, 204, 204));
        cajaCorreo.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        cajaCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCorreoActionPerformed(evt);
            }
        });

        etiquetaContraseña.setBackground(new java.awt.Color(255, 51, 51));
        etiquetaContraseña.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        etiquetaContraseña.setForeground(new java.awt.Color(255, 255, 0));
        etiquetaContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaContraseña.setText("Contraseña");
        etiquetaContraseña.setToolTipText("");
        etiquetaContraseña.setOpaque(true);

        cajaContraseña.setBackground(new java.awt.Color(204, 204, 204));
        cajaContraseña.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N

        etiquetaEstado.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        etiquetaEstado.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaEstado.setText("Nombre");

        Iniciar.setBackground(new java.awt.Color(204, 204, 0));
        Iniciar.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        Iniciar.setForeground(new java.awt.Color(0, 153, 0));
        Iniciar.setText("INICIAR");
        Iniciar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        Iniciar.setBorderPainted(false);
        Iniciar.setFocusable(false);
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });

        iconoTeacher.setBackground(new java.awt.Color(30, 30, 30));
        iconoTeacher.setForeground(new java.awt.Color(30, 30, 30));
        iconoTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenProyectoTopicos/teacherRedm.png"))); // NOI18N
        iconoTeacher.setText("jButton1");
        iconoTeacher.setBorderPainted(false);
        iconoTeacher.setContentAreaFilled(false);
        iconoTeacher.setPreferredSize(new java.awt.Dimension(80, 50));
        iconoTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconoTeacherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insertImagen3Layout = new javax.swing.GroupLayout(insertImagen3);
        insertImagen3.setLayout(insertImagen3Layout);
        insertImagen3Layout.setHorizontalGroup(
            insertImagen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertImagen3Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(insertImagen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiquetaCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaContraseña))
                .addGap(18, 18, 18)
                .addGroup(insertImagen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cajaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertImagen3Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(insertImagen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertImagen3Layout.createSequentialGroup()
                        .addComponent(Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(310, 310, 310))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertImagen3Layout.createSequentialGroup()
                        .addComponent(iconoTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(296, 296, 296))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertImagen3Layout.createSequentialGroup()
                        .addComponent(etiquetaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))))
        );
        insertImagen3Layout.setVerticalGroup(
            insertImagen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertImagen3Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(etiquetaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iconoTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(insertImagen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertImagen3Layout.createSequentialGroup()
                        .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cajaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(cajaCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertImagen3Layout.createSequentialGroup()
                        .addComponent(etiquetaNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etiquetaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(etiquetaCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(etiquetaEstado)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insertImagen3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insertImagen3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void animacionTetxto(){
        
    }
    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed

        //DE ESTA CLASE VOY A CREAR UN OBJETO 
        this.Loggin = new logginU();
        
        
        //CON ESTA CADENA RECIBO EL NOMBRE DEL USUARIO 
        String usuario = this.cajaNombre.getText();
        //CON ESTA CADENA ESTABLEZCO EL NOMBRE DE USUARIO EN EL OBJETO
        this.Loggin.setNickname(usuario);
        
         //CON ESTA CADENA RECIBO LA CONTRASEÑA DEL USUARIO 
        String password = this.cajaContraseña.getText();
        //CON ESTA CADENA ESTABLEZCO LA CONTRASEÑA DEL USUARIO EN EL OBJETO
        this.Loggin.setContraseña(password);
        
         //CON ESTA CADENA RECIBO EL CORREO DEL USUARIO 
        String email = this.cajaCorreo.getText();
        //CON ESTA CADENA ESTABLEZCO EL CORREO DEL USUARIO EN EL OBJETO
        this.Loggin.setCorreo(email);
        
        //GUARDAR EN LA BASE DE DATOS 
        boolean resultado = this.crud.insert(sql.insertlogginU(this.Loggin));
        
        if (resultado){
            JOptionPane.showMessageDialog(null, "Insertado correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "Ocurrio un error en la insercion de los datos");
        }
        
        //MULTIHILOS 
        //TRANSICION ENTRE EL REGISTRO Y LA VENTANA DE INFOJ
        Thread mostrarEstado = new Thread(() -> {
        try {
            String nameU = cajaNombre.getText();
        //El texto de la etiqueta sera cambiado por el mensaje dentro del metodo
            etiquetaEstado.setText("Hola " + nameU + ",te has registrado correctamente");
            Thread.sleep(1); // Simulando una pausa
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        //Actalizar la etiqueta para que sea visible        
        etiquetaEstado.setVisible(true);
    }); //FIN HILO 1
        Thread cambiarGUI = new Thread(() -> {
        try {
            Thread.sleep(1500); // Simulando una pausa
            infoJugador ingresarStats = new infoJugador();
            ingresarStats.setVisible(true);
            this.dispose();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }); //FIN HILO 2
        mostrarEstado.start();
        cambiarGUI.start();
    }//GEN-LAST:event_IniciarActionPerformed

    private void cajaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNombreActionPerformed

    private void cajaCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaCorreoActionPerformed

    private void iconoTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconoTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iconoTeacherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logginUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iniciar;
    private javax.swing.JTextField cajaContraseña;
    private javax.swing.JTextField cajaCorreo;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JLabel etiquetaContraseña;
    private javax.swing.JLabel etiquetaCorreo;
    private javax.swing.JLabel etiquetaEstado;
    private javax.swing.JLabel etiquetaNombre1;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JButton iconoTeacher;
    private practicas.tema2.insertImagen insertImagen3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}

