/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacesGUI;

import static java.lang.Thread.sleep;
import usoBD.conexion;

/**
 *
 * @author fanma
 */
public class pantaInicio extends javax.swing.JFrame {
    
    /**
     * Creates new form usojLabel
     */
    public pantaInicio() {
        initComponents();
        etiquetaConexion.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insertImagen2 = new practicas.tema2.insertImagen();
        jLabel1 = new javax.swing.JLabel();
        Iniciar = new javax.swing.JButton();
        etiquetaConexion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(350, 100));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Oswald SemiBold", 0, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("The Student Rules");

        Iniciar.setBackground(new java.awt.Color(255, 255, 0));
        Iniciar.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        Iniciar.setForeground(new java.awt.Color(0, 255, 0));
        Iniciar.setText("INICIAR SESION");
        Iniciar.setBorder(new javax.swing.border.MatteBorder(null));
        Iniciar.setBorderPainted(false);
        Iniciar.setDefaultCapable(false);
        Iniciar.setFocusPainted(false);
        Iniciar.setHideActionText(true);
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });

        etiquetaConexion.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        etiquetaConexion.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaConexion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaConexion.setText("Nombre");

        javax.swing.GroupLayout insertImagen2Layout = new javax.swing.GroupLayout(insertImagen2);
        insertImagen2.setLayout(insertImagen2Layout);
        insertImagen2Layout.setHorizontalGroup(
            insertImagen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertImagen2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 85, Short.MAX_VALUE))
            .addGroup(insertImagen2Layout.createSequentialGroup()
                .addGroup(insertImagen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertImagen2Layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(insertImagen2Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(etiquetaConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        insertImagen2Layout.setVerticalGroup(
            insertImagen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertImagen2Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(etiquetaConexion)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insertImagen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insertImagen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        //MULTIHILOS
        //CONEXION AL SERVIDOR CON MSJ RETROCESO
        conexion.iniciar();
        Thread proceso1 = new Thread(() -> {
            try {
                if (conexion.Conexion !=null){
                    etiquetaConexion.setText("Conectado al servidor exitosamente");
                } else {
                    etiquetaConexion.setText("Ocurrio un fallo en la conexion");
                }
                Thread.sleep(1); // Simulando una pausa
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            etiquetaConexion.setVisible(true);
        }); //FIN HILO 1
        //HILO PARA PASAR A LA SIGUIENTE VENTANA CON RETROCESO
        Thread proceso2 = new Thread(() -> {
            try {
                Thread.sleep(1500); // Simulando una pausa
                logginUsuarios ingresarLog = new logginUsuarios();
                ingresarLog.setVisible(true);
                this.dispose();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }); //FIN HILO 2
        proceso1.start();
        proceso2.start();
    }//GEN-LAST:event_IniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iniciar;
    private javax.swing.JLabel etiquetaConexion;
    private practicas.tema2.insertImagen insertImagen2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
